name: Build and Test  
  
on:  
  push:  
  pull_request:  
    branches: [ master ]  
  
jobs:  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2  
  
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1  
      with:  
        dotnet-version: '5.0'  # update this to your .NET version  
  
    - name: Build  
      run: dotnet build DdfGuide.Core/DdfGuide.Core.csproj  
  
    - name: Test  
      run: dotnet test DdfGuide.Tests/DdfGuide.Tests.csproj  
